export const FETCH_MESSAGE_REQUEST = 'MAIN/FETCH_MESSAGE_REQUEST';
export const FETCH_MESSAGE_SUCCESS = 'MAIN/FETCH_MESSAGE_SUCCESS';
export const FETCH_MESSAGE_FAILURE = 'MAIN/FETCH_MESSAGE_FAILURE';
